### ISSUE TITLE
[BUG] add_columns method produces duplicate columns on overwriting

### ISSUE THREAD

**Issue by Priya2698** [robustness-gym/meerkat#119]
`add_column` method, when used with `overwrite=True`, produces a duplicate column.

Code:
```
dp = mk.DataPanel({
    'text': ['The quick brown fox.', 'Jumped over.', 'The lazy dog.'],
    'label': [0, 1, 0]
})

dp.add_column("label", [1,2,3], overwrite=True)
```
`dp.columns` gives `['text', 'label', 'index', 'label']`. On printing this `DataPanel`, both these `label`columns have the new data.

**Comment by seyuboglu** [comment]
`add_column` is reading the column to `visible_columns` even if it already exists.

#108 will close this: it fixes the issue and adds a test checking for the correct behavior
