### ISSUE TITLE
[BUG] "'numpy.ndarray' object is not callable" when creating `ImageColumn`

### ISSUE THREAD

**Issue by AmanDesai-coder** [robustness-gym/meerkat#122]
**Describe the bug**

Error: TypeError: 'numpy.ndarray' object is not callable

**To Reproduce**

1. Code:
import pandas as pd
print(pd.__version__)
import os
import meerkat as mk
import numpy as np

from meerkat.contrib.imagenette import download_imagenette

BASE_DIR = "./datasets"
dataset_dir = download_imagenette(BASE_DIR);

dp = mk.DataPanel.from_csv(os.path.join(dataset_dir, "imagenette.csv"))
dp["img"] = mk.ImageColumn.from_filepaths(filepaths=dp["img_path"])
dp.head()

2. Run Code

3. Error: TypeError: 'numpy.ndarray' object is not callable

1. Code snippet '....'
2. Instructions (Run '...')
3. Errors and traceback '....'

Include any relevant screenshots.

**Expected behavior**
I expected a new ImageColumn called "img" to be created.

**System Information**
MacOS, Linux
pandas version 1.2.4

**Additional context**
N/A

**Comment by seyuboglu** [comment]
This is working now on dev
