### ISSUE TITLE
[BUG] Can't overwrite save with block/manager.py

### ISSUE THREAD

**Issue by lorr1** [robustness-gym/meerkat#127]
In `block/manager.py` line 188, there's a call to `os.makedirs(block_dirs)`. If the folder already exists, this throws an error. I wasnt' sure how you folks wanted to handle this. I generally think people will commonly save over folders so maybe have the exists ok flag turned on?

**Comment by ad12** [comment]
Yup - `exists_ok` should be set to True. Feel free to drop a PR for that if you'd like, or we add the fix with the set of bugs we'll be handling this week.
