### ISSUE TITLE
[BUG] DataPanel returns dict for _state_keys, not set

### ISSUE THREAD

**Issue by gtmtg** [robustness-gym/meerkat#223]
**Describe the bug**
DataPanel's default return type for `_state_keys` is an [empty dict](https://github.com/robustness-gym/meerkat/blob/d1528046fdaa4462794b38e3eb9d7c2ad9509e5a/meerkat/datapanel.py#L844), not an empty set. This causes a crash for subclasses of DataPanel that attempt to union their `_state_keys` with `super()`'s `_state_keys`.

    File ~/Dropbox/Projects/actively/lib/src/actively/datasets/columns.py:54, in ActivelyDataset._state_keys(cls)
         52 @classmethod
         53 def _state_keys(cls) -> Set[str]:
    ---> 54     return super(ActivelyDataset, cls)._state_keys().union({"name"})

    AttributeError: 'dict' object has no attribute 'union'

**Comment by seyuboglu** [comment]
#224 just got merged into dev which should fix this
