### ISSUE TITLE
[BUG] Typo in setup.py for Cython dependency causes installation to sometimes fail

### ISSUE THREAD

**Issue by gtmtg** [robustness-gym/meerkat#262]
Hi! I believe there's a typo in setup.py around the Cython dependency. This:

        "semver>=2.13.0",
      > "multiprocess>=0.70.11" "Cython>=0.29.21",
        "progressbar>=2.5",

[(source)](https://github.com/robustness-gym/meerkat/blob/1e290eab180b1692403a7f695e1dbe2165a57efe/setup.py#L47)

is missing a comma, causing the strings to be concatenated; it should be:

        "semver>=2.13.0",
        "multiprocess>=0.70.11",
        "Cython>=0.29.21",
        "progressbar>=2.5",

This is causing installation to fail in some cases (for some reason, with Poetry 1.2 or above but not with earlier versions of poetry) for us with an error like: "multiprocess: Could not parse version constraint: >=0.70.11Cython"

**Comment by krandiash** [comment]
Sorry about the delay, we're dealing with a couple of paper deadlines. I just merged the fix you suggested (#264) into the `dev` branch. I recommend primarily using that branch, since it's easier for us to push fixes there quickly without doing a larger release (and we keep it stable).
