### ISSUE TITLE
[BUG] Downloading imagenet does not work

### ISSUE THREAD

**Issue by MaxFBurg** [robustness-gym/meerkat#263]
**Describe the bug**
Downloading imagenet like this does not work:
```python
dp = mk.datasets.get(
    "imagenet", 
    dataset_dir="/home/ec2-user/data/imagenet1k",
    download=True,
)
```
Fails with `FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/data/imagenet1k/ILSVRC/ImageSets/CLS-LOC/train_cls.txt'`

**To Reproduce**
Steps and code snippet that reproduce the behavior:

1. Code snippet '....'
2. Instructions (Run '...')
3. Errors and traceback '....'

See above

Include any relevant screenshots.

**Expected behavior**
Should download imagenet1k to the specified `dataset_dir`.

**System Information**
 - OS: Linux
 - Versions for RG and relevant dependencies `meerkat-ml` (latest)

**Additional context**

**Comment by krandiash** [comment]
Hi, thanks for the report, try:
```python
dp = mk.datasets.get(
    "imagenet", 
    dataset_dir="/home/ec2-user/data/imagenet1k",
    download_mode="force",
)
```
