### ISSUE TITLE
Make `DataPanel(dp)` return some shallow copied version of the original `dp`.

### ISSUE THREAD

**Issue by ad12** [robustness-gym/meerkat#56]
## Issue
It is very natural for users (and developers) to construct new DataPanel objects from existing ones via `DataPanel(dp)`.

## Important Aside
An unexpected consequence of this issue is finding a good way to stratify which attributes should be recomputed and which should simply be shallow copied over.

As an example, two attributes that every DataPanel has is `_data` and `_identifier`. `_data` is typically large and heavy-weight, so we will almost always want to shallow copy it. `_identifier` is quite lightweight and may be unique to different DataPanels, so maybe this is a property we recompute each time in `__init__`. Note this is just an example, we may want the identifier to persist.

This is especially relevant for subclassing `DataPanel`. As of PR #57, `self.from_batch()` is used to construct new DataPanel containers from existing ones with shared underlying data. However, as the PR mentions, `self.from_batch()` is called by many other ops (`_get`, `merge`, `concat`, etc.), and none of these methods have a seamless way of passing arguments other than `data` to `__init__`.

An example of this is EntityDataPanel, where the index_column should be passed from the current instance to the newly constructed instance. Because there is no way to plumb that information through different calls, the initializer of EntityDataPanel gets called with EntityDataPanel(index_column=None) even if the current instance has an index column. This results in a new column "_ent_index" being added to the new EntityDataPanel.

## Proposed Solution 1
Implement a private instance method called `_clone(data=None, visible_columns=None...) -> DataPanel/subclass` which implements the default functionality for how to construct a new DataPanel with the relevant arguments to plumb from current instance to new instance. We can then call `self._clone(data=data, visible_columns-optional)` instead of `self.from_batch()` in ops like `_get`, `merge`, `concat`, etc.

Let's consider the `EntityDataPanel` case. We want to plumb `self.index_column` from a current `EntityDataPanel` to all `EntityDataPanel`s constructed in its image. `._clone` will look something like 

```python
class EntityDataPanel:
    def _clone(self, data=None) -> EntityDataPanel:
        if data is None:
            data = self.data
        return EntityDataPanel(data, identifier=identifier, index_column=self.index_column)
```

We can then have ops like `DataPanel._get()` for example use `self._clone()` instead of `self.from_batch()`. For example
```python
class DataPanel:
    def _get(self, idx, materialize=False):
        ...
        # example cases where `index` returns a datapanel
        elif isinstance(index, slice):
            # slice index => multiple row selection (DataPanel)
            # return self.from_batch(
            #    {
            #        k: self._data[k]._get(index, materialize=materialize)
            #        for k in self.visible_columns
            #    })
            return self._clone({
                k: self._data[k]._get(index, materialize=materialize)
                for k in self.visible_columns
            })
        ...
```

## Proposed Solution 2
Instead of having developers reimplement `._clone()`, we can have them implement something like `_state_keys()` but for __init__ args. Something like `._clone_kwargs()`:

```python
class EntityDataPanel:
    def _clone_kwargs(self) -> EntityDataPanel:
        default_kwargs = super()._clone_kwargs()
        default_kwargs.update({"index_column": self.index_column})
        return default_kwargs
```

```python
class DataPanel:
    def _default_kwargs(self):
        return {"data": self.data, "identifier": self.identifier}

    def _clone(self, **kwargs):
        default_kwargs = self._clone_kwargs()
        if kwargs:
            default_kwargs.update(kwargs)
        return self.__class__(**default_kwargs)
```

**Comment by seyuboglu** [comment]
I like solution 2 better, since folks could still reimplement `._clone()` if they need to

**Comment by lorr1** [comment]
Agreed. I like the second option better. I already have to modify the state_keys so EDP stuff gets saved correctly, so having a second for init args makes a lot of sense.

**Comment by krandiash** [comment]
+1
